version: "3.7"
services:
  backup:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PBS_REPOSITORY: "crewzone@pbs@pbs.becker-software.de:443:nas"
      PBS_PASSWORD: "X@3OQ#mIIQp9!GFIce#uCVpo8!"
      PBS_ENCRYPTION_PASSWORD: "%z*^hymf2J^e72P3E*"
      PBS_FINGERPRINT: "97:51:30:69:e5:2e:df:01:14:60:8a:0e:55:82:58:da:36:69:6e:be:5e:44:04:d9:2e:ae:11:92:69:02:59:0f"
      PGHOST: "10.250.1.4"
      PGPORT: "5432"
      PGDATABASE: "postgres"
      PGPASSWORD: "1XE^1k7sET%#5c3Vtxw@UkUK%!"
      PGUSER: "elbgoodsbackupuser"
      PGDBSELECT: "SELECT datname FROM pg_database WHERE datistemplate = false AND (datname LIKE 'dev_%' OR datname LIKE 'staging_%' OR datname LIKE 'production_%');"

      S3_ENDPOINT: "https://s3.crewzone.com/"
      S3_ACCESS: "rWLP3vJzP7-backup"
      S3_SECRET: "lfr2nFDre0YhpIwBXWpXhvTCW06ULyME"

      MONGO_URL: "mongodb+srv://pbs_backup:ez2stuBzGzAu5OOw@productionplatformlive.nrpha.mongodb.net/?retryWrites=true&w=majority"

      BACKUP_ID: "mongo"
      BACKUP_SOURCE: "MONGO"
      PBC_NAMESPACE: "elbgoods/prg/crewzone"
    volumes:
      - ./backup:/app/backup
      - ./backup.sh:/app/backup.sh
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 100000